-- MySQL Script generated by MySQL Workbench
-- Вт 10 авг 2021 10:27:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Категория`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Категория` (
  `Категория` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Категория`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Места и ряды`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Места и ряды` (
  `Зал` VARCHAR(45) NOT NULL,
  `Ряд` INT NOT NULL,
  `Место` INT NOT NULL,
  `Категория` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Зал`, `Ряд`, `Место`),
  INDEX `Категория_idx` (`Категория` ASC) VISIBLE,
  CONSTRAINT `Категория`
    FOREIGN KEY (`Категория`)
    REFERENCES `mydb`.`Категория` (`Категория`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Билеты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Билеты` (
  `idБилеты` INT NOT NULL AUTO_INCREMENT,
  `Дата` DATE NOT NULL,
  `Время` DATETIME NOT NULL,
  `Зал` VARCHAR(45) NOT NULL,
  `Ряд` INT NOT NULL,
  `Место` INT NOT NULL,
  `Продан` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idБилеты`),
  INDEX `Зал_idx` (`Зал` ASC) VISIBLE,
  INDEX `Ряд_idx` (`Ряд` ASC) VISIBLE,
  INDEX `Место_idx` (`Место` ASC) VISIBLE,
  CONSTRAINT `Зал`
    FOREIGN KEY (`Зал`)
    REFERENCES `mydb`.`Места и ряды` (`Зал`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ряд`
    FOREIGN KEY (`Ряд`)
    REFERENCES `mydb`.`Места и ряды` (`Ряд`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Место`
    FOREIGN KEY (`Место`)
    REFERENCES `mydb`.`Места и ряды` (`Место`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Залы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Залы` (
  `idЗал` VARCHAR(45) NOT NULL,
  `Наименование зала` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idЗал`),
  UNIQUE INDEX `Наименование зала_UNIQUE` (`Наименование зала` ASC) VISIBLE,
  CONSTRAINT `idЗал`
    FOREIGN KEY (`idЗал`)
    REFERENCES `mydb`.`Места и ряды` (`Зал`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Страна`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Страна` (
  `Название страны` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Название страны_UNIQUE` (`Название страны` ASC) VISIBLE,
  PRIMARY KEY (`Название страны`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Жанр`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Жанр` (
  `Название Жанра` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Название Жанра`),
  UNIQUE INDEX `Название Жанра_UNIQUE` (`Название Жанра` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Фильмы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Фильмы` (
  `idФильма` INT NOT NULL AUTO_INCREMENT,
  `Название фильма` VARCHAR(45) NOT NULL,
  `Производство` VARCHAR(45) NOT NULL,
  `Год выпуска` DATE NOT NULL,
  `Жанр` VARCHAR(45) NOT NULL,
  `Длительность` INT NOT NULL,
  PRIMARY KEY (`idФильма`),
  INDEX `Производство_idx` (`Производство` ASC) VISIBLE,
  INDEX `Жанр_idx` (`Жанр` ASC) VISIBLE,
  CONSTRAINT `Производство`
    FOREIGN KEY (`Производство`)
    REFERENCES `mydb`.`Страна` (`Название страны`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Жанр`
    FOREIGN KEY (`Жанр`)
    REFERENCES `mydb`.`Жанр` (`Название Жанра`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сеансы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сеансы` (
  `idsession` INT NOT NULL AUTO_INCREMENT,
  `Время` DATETIME NOT NULL,
  `Зал` VARCHAR(45) NOT NULL,
  `Фильм` INT NOT NULL,
  PRIMARY KEY (`idsession`, `Зал`, `Время`),
  INDEX `Зал_idx` (`Зал` ASC) VISIBLE,
  INDEX `Фильм_idx` (`Фильм` ASC) VISIBLE,
  CONSTRAINT `Зал`
    FOREIGN KEY (`Зал`)
    REFERENCES `mydb`.`Залы` (`idЗал`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Фильм`
    FOREIGN KEY (`Фильм`)
    REFERENCES `mydb`.`Фильмы` (`idФильма`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Цены`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Цены` (
  `idЦены` INT NOT NULL AUTO_INCREMENT,
  `Дата` VARCHAR(45) NOT NULL,
  `Время` DATE NOT NULL,
  `Категория` VARCHAR(45) NOT NULL,
  `Цена` INT NOT NULL,
  PRIMARY KEY (`idЦены`),
  INDEX `Категория_idx` (`Категория` ASC) VISIBLE,
  CONSTRAINT `Категория`
    FOREIGN KEY (`Категория`)
    REFERENCES `mydb`.`Категория` (`Категория`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
