-- MySQL Script generated by MySQL Workbench
-- Вт 17 авг 2021 08:51:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Страна`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Страна` (
  `Название страны` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Название страны_UNIQUE` (`Название страны` ASC) VISIBLE,
  PRIMARY KEY (`Название страны`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Жанр`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Жанр` (
  `Название Жанра` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Название Жанра`),
  UNIQUE INDEX `Название Жанра_UNIQUE` (`Название Жанра` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Фильмы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Фильмы` (
  `idФильма` INT NOT NULL AUTO_INCREMENT,
  `Название фильма` VARCHAR(45) NOT NULL,
  `Производство` VARCHAR(45) NOT NULL,
  `Год выпуска` DATE NOT NULL,
  `Жанр` VARCHAR(45) NOT NULL,
  `Длительность` INT NOT NULL,
  PRIMARY KEY (`idФильма`),
  INDEX `Производство_idx` (`Производство` ASC) VISIBLE,
  INDEX `Жанр_idx` (`Жанр` ASC) VISIBLE,
  CONSTRAINT `Производство`
    FOREIGN KEY (`Производство`)
    REFERENCES `mydb`.`Страна` (`Название страны`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Жанр`
    FOREIGN KEY (`Жанр`)
    REFERENCES `mydb`.`Жанр` (`Название Жанра`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Сеансы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Сеансы` (
  `idsession` VARCHAR(45) NOT NULL,
  `Время` DATETIME NOT NULL,
  `Фильм` INT NOT NULL,
  PRIMARY KEY (`idsession`, `Время`),
  INDEX `Фильм_idx` (`Фильм` ASC) VISIBLE,
  CONSTRAINT `Фильм`
    FOREIGN KEY (`Фильм`)
    REFERENCES `mydb`.`Фильмы` (`idФильма`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'fk_Сеансы_1';


-- -----------------------------------------------------
-- Table `mydb`.`Цены`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Цены` (
  `idЦены` INT NOT NULL AUTO_INCREMENT,
  `Дата` VARCHAR(45) NOT NULL,
  `Время` DATE NOT NULL,
  `Сеанс` VARCHAR(45) NOT NULL,
  `Цена` INT NOT NULL,
  PRIMARY KEY (`idЦены`),
  INDEX `Сеанс_idx` (`Сеанс` ASC) VISIBLE,
  CONSTRAINT `Сеанс`
    FOREIGN KEY (`Сеанс`)
    REFERENCES `mydb`.`Сеансы` (`idsession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Залы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Залы` (
  `Наименование зала` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `Наименование зала_UNIQUE` (`Наименование зала` ASC) VISIBLE,
  PRIMARY KEY (`Наименование зала`),
  CONSTRAINT `Наименование зала`
    FOREIGN KEY (`Наименование зала`)
    REFERENCES `mydb`.`Сеансы` (`idsession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Место`
-- -----------------------------------------------------
