-- MySQL Script generated by MySQL Workbench
-- Ср 11 авг 2021 15:48:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `likes` DEFAULT CHARACTER SET utf8 ;
USE `likes` ;

-- -----------------------------------------------------
-- Table `likes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likes`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `iduser` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`voted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likes`.`voted` (
  `who` INT NOT NULL,
  `toWhom` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_voted_1_idx` (`who` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_voted_2_idx` (`toWhom` ASC) VISIBLE,
  CONSTRAINT `fk_voted_1`
    FOREIGN KEY (`who`)
    REFERENCES `likes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_voted_2`
    FOREIGN KEY (`toWhom`)
    REFERENCES `likes`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
