-- MySQL Script generated by MySQL Workbench
-- Пн 09 авг 2021 10:02:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema likes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `likes` DEFAULT CHARACTER SET utf8 ;
USE `likes` ;

-- -----------------------------------------------------
-- Table `likes`.`voted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likes`.`voted` (
  `idvoted` INT NOT NULL AUTO_INCREMENT,
  `who` INT NOT NULL,
  `toWhom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvoted`, `who`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `likes`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `likes`.`user` (
  `username` VARCHAR(45) NOT NULL,
  `iduser` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`iduser`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `likes`.`voted` (`who`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
